# Generated by Django 5.2.5 on 2025-09-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriTechApp', '0003_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
